@startuml

start
:接收POST /base/mat请求;

:@PreAuthorize权限校验;
if (权限校验通过?) then (是)
else (否)
  :返回403错误响应;
  stop
endif

:setCreateBy(getUsername());

partition "Service层处理" {
  :setCreateTime(getNowDate());
  :baseMatMapper.insertBaseMat(baseMat);
}

if (影响行数 > 0?) then (是)
  :返回AjaxResult.success;
else (否)
  :返回AjaxResult.error;
endif

stop

@enduml