@startuml
start
:点击新增按钮，填写物料信息;
:前端表单验证;

if (验证通过?) then (是)
  :提交至后端;
  :编码唯一性校验;
  if (编码重复?) then (是)
    :返回错误提示;
    stop
  else (否)
    :设置默认值，插入数据表;
    :返回成功响应，刷新列表;
  endif
else (否)
  :显示错误提示;
  stop
endif

stop

@enduml