@startuml
hide members
skinparam linetype ortho
skinparam nodesep 60
skinparam ranksep 100
skinparam arrowFontSize 18


entity "BASE_MAT_CLASS" as BMC
entity "BASE_MAT" as BM
entity "BASE_MAT_BOM" as BMB
entity "BASE_MAT_GROUP" as BMG

entity "BASE_WAREHOUSE" as BW
entity "BASE_SUPPLIER" as BS
entity "BASE_LOCATION" as BL
entity "BASE_WORKSHOP" as BWS

entity "STOCK_IN_ORDER" as SIO
entity "STOCK_OUT_ORDER" as SOO
entity "STOCK_ALLOT_ORDER" as SAO

entity "STOCK_IN_RETURN" as SIR
entity "STOCK_OUT_RETURN" as SOR
entity "STOCK_PROD_ORDER" as SPO

entity "STOCK_MAT_LABEL" as SML
entity "STOCK_INFO" as SI
entity "STOCK_RECORD" as SR

' === 布局控制 ===
BMC -[hidden]down- BW
BW -[hidden]down- SIO
SIO -[hidden]down- SIR
SIR -[hidden]down- SML

BMC -[hidden]right- BM
BM -[hidden]right- BMB
BMB -[hidden]right- BMG

BW -[hidden]right- BS
BS -[hidden]right- BL
BL -[hidden]right- BWS

SIO -[hidden]right- SOO
SOO -[hidden]right- SAO

SIR -[hidden]right- SOR
SOR -[hidden]right- SPO

SML -[hidden]right- SI
SI -[hidden]right- SR

' --- 基础数据关联 ---
BMB }o--left--|| BM : 父子物料
BMG }o--left--|| BM : 物料组归属
BMC ||--right--o{ BM : 物料分类归属
BW ||--right--o{ BL : 包含货位

' --- 入库业务 ---
SIO }o--up--|| BM : 入库物料
SIO }o--up--|| BW : 入库仓库
SIO }o--up--|| BS : 供应商
SIO ||--down--o{ SML : 生成标签
SIR }o--up--|| SIO : 关联入库单

' --- 出库业务 ---
SPO ||--up--o{ SOO : 生成出库单
SOO }o--up--|| BW : 出库仓库
SOO }o--up--|| BWS : 领料车间
SOR }o--up--|| SOO : 关联出库单

' --- 调拨业务 ---
SAO }o--left--|| SOO : 调拨出库
SAO }o--left--|| SIO : 调拨入库

' --- 库存与流水 ---
SI }o--up--|| BM : 库存物料
SI }o--up--|| BW : 所在仓库
SI ||--right--o{ SR : 产生流水
SML }o--up--|| BM : 标签物料
SR }o--left--|| SML : 关联标签

@enduml

